/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.lugar.view.cliente;

import com.lugar.controller.Conexao;
import com.lugar.model.Produto;
import com.lugar.model.ProdutosTableModel;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import javax.swing.JTable;

/**
 *
 * @author lugar
 */
public class Carrinho extends javax.swing.JDialog {

    private Conexao conexao;
    private int idUsuario;
    private List<Produto> listaProdutos;
    private ProdutosTableModel modeloTabela;
    private Map<Integer, Integer> listaProdutosCarrinho;
    private java.awt.Frame pai;

    public Carrinho(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.pai = parent;
        initComponents();
    }

    public Carrinho(java.awt.Frame parent, boolean modal, Map<Integer, Integer> listaProdutosCarrinho) {
        super(parent, modal);

        this.conexao = new Conexao();
        this.listaProdutosCarrinho = listaProdutosCarrinho;
        this.montaListaProdutos();

        initComponents();

        tabelaProdutos.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent mouseEvent) {
                JTable tabela = (JTable) mouseEvent.getSource();
                Point ponto = mouseEvent.getPoint();
                int linha = tabela.rowAtPoint(ponto);
                // Clique duplo
                if (mouseEvent.getClickCount() == 2 && tabela.getSelectedRow() != -1) {
                    chamaTelaEdicaoProdutoCarrinho((int) modeloTabela.getValueAt(linha, 0));
                }
            }
        });
    }

    public Map<Integer, Integer> getListaProdutosCarrinho() {
        return this.listaProdutosCarrinho;
    }

    private ProdutosTableModel getModeloTabela() {
        this.atualizaModeloTabela();
        return this.modeloTabela;
    }

    private void montaListaProdutos() {
        this.listaProdutos = new ArrayList<Produto>();
        for (int id : listaProdutosCarrinho.keySet()) {
            Produto produto = conexao.buscaProduto(id);
            produto.setQuantidade(listaProdutosCarrinho.get(id));
            this.listaProdutos.add(produto);
        }
    }

    private void atualizaModeloTabela() {
        for (Produto produto : listaProdutos) {
            produto.setQuantidade(
                    listaProdutosCarrinho.get(produto.getId()));
        }
        this.modeloTabela = new ProdutosTableModel(this.listaProdutos);
    }

    private void atualizaTabela() {
        this.atualizaModeloTabela();
        tabelaProdutos.setModel(this.modeloTabela);
    }

    // Fluxo de telas
    private void chamaTelaEdicaoProdutoCarrinho(int id) {
        Produto produto = this.conexao.buscaProduto(id);
        int quantidadeCarrinho = this.listaProdutosCarrinho.get(id);
        AdicaoProdutoCarrinho adicaoProdutoCarrinho = new AdicaoProdutoCarrinho(this.pai, true, produto, quantidadeCarrinho);
        adicaoProdutoCarrinho.setVisible(true);
        int quantidadeComprada = adicaoProdutoCarrinho.getQuantidade();
        this.listaProdutosCarrinho.put(id, quantidadeComprada);
        this.atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painelTabela = new javax.swing.JPanel();
        painelRolavelTabela = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Carrinho");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        painelTabela.setLayout(new java.awt.BorderLayout());

        tabelaProdutos.setModel(this.getModeloTabela());
        tabelaProdutos.getTableHeader().setReorderingAllowed(false);
        painelRolavelTabela.setViewportView(tabelaProdutos);

        painelTabela.add(painelRolavelTabela, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(painelTabela, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Carrinho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Carrinho dialog = new Carrinho(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane painelRolavelTabela;
    private javax.swing.JPanel painelTabela;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
