/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.lugar.view.cliente;

import com.lugar.controller.Conexao;
import com.lugar.model.ProdutoPersonalizado;
import javax.swing.JOptionPane;

/**
 *
 * @author lugar
 */
public class CriacaoProdutoPersonalizado extends javax.swing.JDialog {

    private int idProduto;
    private int quantidade;
    private String tipo;

    public int getIdProduto() {
        return this.idProduto;
    }

    public int getQuantidade() {
        return this.quantidade;
    }

    public CriacaoProdutoPersonalizado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.idProduto = -1;
        this.tipo = "Bolo";
        initComponents();
        this.trocaPainel();
    }

    private void trocaPainel() {
        if (this.tipo.equals("Bolo")) {
            this.painelCamposBolo.setVisible(true);
            this.painelCamposTrufa.setVisible(false);
        } else {
            this.painelCamposBolo.setVisible(false);
            this.painelCamposTrufa.setVisible(true);
        }
    }

    private void criaProdutoPersonalizado() {
        if (this.tipo.equals("Bolo")) {
            String recheioForm = this.comboBoxRecheioBolo1.getSelectedItem().toString();
            String coberturaForm = this.comboBoxCoberturaBolo.getSelectedItem().toString();
            String detalheForm = this.areaTextoDetalheBolo.getText().trim();

            ProdutoPersonalizado produtoPersonalizado
                    = new ProdutoPersonalizado(this.idProduto, this.tipo + " - " + recheioForm, 100,
                            99999, recheioForm, coberturaForm, detalheForm);

            this.idProduto = Conexao.insereProdutoPersonalizado(produtoPersonalizado);
        }

        if (this.idProduto > -1) {
            JOptionPane.showMessageDialog(null, "Produto adicionado ao carrinho!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Não foi possível adicionar o produto! Tente novamente mais tarde.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painelFormulario = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        painelInformacoesProduto = new javax.swing.JPanel();
        textoPrecoProduto = new javax.swing.JLabel();
        painelTipoQuantidade = new javax.swing.JPanel();
        textoTipo = new javax.swing.JLabel();
        comboBoxTipo = new javax.swing.JComboBox<>();
        textoQuantidade = new javax.swing.JLabel();
        campoQuantidade = new javax.swing.JSpinner();
        painelCamposTrufa = new javax.swing.JPanel();
        textoRecheioTrufa = new javax.swing.JLabel();
        comboBoxRecheioTrufa = new javax.swing.JComboBox<>();
        textoCoberturaTrufa = new javax.swing.JLabel();
        comboBoxCoberturaTrufa = new javax.swing.JComboBox<>();
        textoDetalheTrufa = new javax.swing.JLabel();
        painelAreaTextoDetalheTrufa = new javax.swing.JScrollPane();
        areaTextoDetalheTrufa = new javax.swing.JTextPane();
        painelCamposBolo = new javax.swing.JPanel();
        textoFormaBolo = new javax.swing.JLabel();
        comboBoxFormaBolo = new javax.swing.JComboBox<>();
        painelCamposRecheiosBolo = new javax.swing.JPanel();
        comboBoxRecheioBolo1 = new javax.swing.JComboBox<>();
        textoCoberturaBolo = new javax.swing.JLabel();
        comboBoxCoberturaBolo = new javax.swing.JComboBox<>();
        textoCorBolo = new javax.swing.JLabel();
        comboBoxCorBolo1 = new javax.swing.JComboBox<>();
        textoDetalheBolo = new javax.swing.JLabel();
        painelAreaTextoDetalheBolo = new javax.swing.JScrollPane();
        areaTextoDetalheBolo = new javax.swing.JTextPane();
        painelBotoes = new javax.swing.JPanel();
        botaoCancelar = new javax.swing.JButton();
        botaoEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar produto ao Carrinho");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        painelFormulario.setLayout(new java.awt.GridBagLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Produto personalizado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        painelFormulario.add(titulo, gridBagConstraints);

        painelInformacoesProduto.setLayout(new java.awt.GridBagLayout());

        textoPrecoProduto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoPrecoProduto.setText("R$ 0,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        painelInformacoesProduto.add(textoPrecoProduto, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        painelFormulario.add(painelInformacoesProduto, gridBagConstraints);

        painelTipoQuantidade.setLayout(new java.awt.GridBagLayout());

        textoTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoTipo.setText("Tipo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelTipoQuantidade.add(textoTipo, gridBagConstraints);

        comboBoxTipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bolo", "Trufa" }));
        comboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTipoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelTipoQuantidade.add(comboBoxTipo, gridBagConstraints);

        textoQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        textoQuantidade.setText("Quantidade:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        painelTipoQuantidade.add(textoQuantidade, gridBagConstraints);

        campoQuantidade.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99999, 1));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        painelTipoQuantidade.add(campoQuantidade, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        painelFormulario.add(painelTipoQuantidade, gridBagConstraints);

        painelCamposTrufa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelCamposTrufa.setLayout(new java.awt.GridBagLayout());

        textoRecheioTrufa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoRecheioTrufa.setText("Recheio:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        painelCamposTrufa.add(textoRecheioTrufa, gridBagConstraints);

        comboBoxRecheioTrufa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morango", "Chocolate", "Beijinho" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        painelCamposTrufa.add(comboBoxRecheioTrufa, gridBagConstraints);

        textoCoberturaTrufa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCoberturaTrufa.setText("Cobertura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        painelCamposTrufa.add(textoCoberturaTrufa, gridBagConstraints);

        comboBoxCoberturaTrufa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate meio amargo", "Chocolate branco" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        painelCamposTrufa.add(comboBoxCoberturaTrufa, gridBagConstraints);

        textoDetalheTrufa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoDetalheTrufa.setText("Detalhe:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        painelCamposTrufa.add(textoDetalheTrufa, gridBagConstraints);

        areaTextoDetalheTrufa.setText("\n\n");
        painelAreaTextoDetalheTrufa.setViewportView(areaTextoDetalheTrufa);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        painelCamposTrufa.add(painelAreaTextoDetalheTrufa, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        painelFormulario.add(painelCamposTrufa, gridBagConstraints);

        painelCamposBolo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        painelCamposBolo.setLayout(new java.awt.GridBagLayout());

        textoFormaBolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoFormaBolo.setText("Forma:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        painelCamposBolo.add(textoFormaBolo, gridBagConstraints);

        comboBoxFormaBolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Redonda com furo - M 18x8", "Redonda com furo - G 21.5x9.5", "Retangular - M 28x19x4.5" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 5);
        painelCamposBolo.add(comboBoxFormaBolo, gridBagConstraints);

        painelCamposRecheiosBolo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Recheios"));
        painelCamposRecheiosBolo.setLayout(new java.awt.GridBagLayout());

        comboBoxRecheioBolo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chocolate meio amargo", "Chocolate branco" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelCamposRecheiosBolo.add(comboBoxRecheioBolo1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 5, 10);
        painelCamposBolo.add(painelCamposRecheiosBolo, gridBagConstraints);

        textoCoberturaBolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCoberturaBolo.setText("Cobertura:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        painelCamposBolo.add(textoCoberturaBolo, gridBagConstraints);

        comboBoxCoberturaBolo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Glacê de limão", "Chantilly" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        painelCamposBolo.add(comboBoxCoberturaBolo, gridBagConstraints);

        textoCorBolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoCorBolo.setText("Cor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        painelCamposBolo.add(textoCorBolo, gridBagConstraints);

        comboBoxCorBolo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Branco", "Amarelo", "Rosa" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        painelCamposBolo.add(comboBoxCorBolo1, gridBagConstraints);

        textoDetalheBolo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoDetalheBolo.setText("Detalhe:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
        painelCamposBolo.add(textoDetalheBolo, gridBagConstraints);

        areaTextoDetalheBolo.setText("\n\n");
        painelAreaTextoDetalheBolo.setViewportView(areaTextoDetalheBolo);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
        painelCamposBolo.add(painelAreaTextoDetalheBolo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        painelFormulario.add(painelCamposBolo, gridBagConstraints);

        painelBotoes.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        painelBotoes.add(botaoCancelar);

        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        painelBotoes.add(botaoEnviar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        painelFormulario.add(painelBotoes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(painelFormulario, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        this.criaProdutoPersonalizado();
//        this.dispose();
    }//GEN-LAST:event_botaoEnviarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    private void comboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTipoActionPerformed
        this.tipo = comboBoxTipo.getSelectedItem().toString();
        this.trocaPainel();
    }//GEN-LAST:event_comboBoxTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CriacaoProdutoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CriacaoProdutoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CriacaoProdutoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CriacaoProdutoPersonalizado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CriacaoProdutoPersonalizado dialog = new CriacaoProdutoPersonalizado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane areaTextoDetalheBolo;
    private javax.swing.JTextPane areaTextoDetalheTrufa;
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JSpinner campoQuantidade;
    private javax.swing.JComboBox<String> comboBoxCoberturaBolo;
    private javax.swing.JComboBox<String> comboBoxCoberturaTrufa;
    private javax.swing.JComboBox<String> comboBoxCorBolo1;
    private javax.swing.JComboBox<String> comboBoxFormaBolo;
    private javax.swing.JComboBox<String> comboBoxRecheioBolo1;
    private javax.swing.JComboBox<String> comboBoxRecheioTrufa;
    private javax.swing.JComboBox<String> comboBoxTipo;
    private javax.swing.JScrollPane painelAreaTextoDetalheBolo;
    private javax.swing.JScrollPane painelAreaTextoDetalheTrufa;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCamposBolo;
    private javax.swing.JPanel painelCamposRecheiosBolo;
    private javax.swing.JPanel painelCamposTrufa;
    private javax.swing.JPanel painelFormulario;
    private javax.swing.JPanel painelInformacoesProduto;
    private javax.swing.JPanel painelTipoQuantidade;
    private javax.swing.JLabel textoCoberturaBolo;
    private javax.swing.JLabel textoCoberturaTrufa;
    private javax.swing.JLabel textoCorBolo;
    private javax.swing.JLabel textoDetalheBolo;
    private javax.swing.JLabel textoDetalheTrufa;
    private javax.swing.JLabel textoFormaBolo;
    private javax.swing.JLabel textoPrecoProduto;
    private javax.swing.JLabel textoQuantidade;
    private javax.swing.JLabel textoRecheioTrufa;
    private javax.swing.JLabel textoTipo;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
