/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.lugar.view.cliente;

import com.lugar.view.VisualizacaoItemProdutoPersonalizado;
import com.lugar.view.VisualizacaoItemProdutoPronto;
import com.lugar.controller.OperacoesPedido;
import com.lugar.model.Item;
import com.lugar.model.Pedido;
import com.lugar.model.Produto;
import com.lugar.model.ProdutoPronto;
import com.lugar.model.tables.ItensTableModel;
import java.awt.Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JTable;

/**
 *
 * @author lugar
 *Anna Júlia de Almeida Lucas - 2021760029
 *Celso Gabriel Dutra Almeida Malosto - 202176002
 *Lucas Paiva dos Santos - 2021760026
 *Rodrigo Soares de Assis - 202176027
 */
public class VisualizacaoPedido extends javax.swing.JDialog {

    private int id;
    private java.awt.Frame pai;
    private OperacoesPedido operacoesPedido;
    private ItensTableModel modeloTabela;

    public VisualizacaoPedido(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public VisualizacaoPedido(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        this.id = id;
        this.pai = parent;
        this.operacoesPedido = new OperacoesPedido();
        Pedido pedido = operacoesPedido.busca(id);
        this.modeloTabela = new ItensTableModel(pedido.getListaItens());
        initComponents();

        // Pedido
        textoValorPreenchido.setText(pedido.getValorFormatado());
        textoSolicitadoPreenchido.setText(pedido.getDiaHoraFormatado());
        textoEntregaPreenchido.setText(pedido.getDataEntregaFormatada());
        painelTextoComentario.setText(pedido.getComentario());
        textoEstadoPreenchido.setText(pedido.getEstadoFormatado());

        tabelaItens.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent mouseEvent) {
                JTable tabela = (JTable) mouseEvent.getSource();
                Point ponto = mouseEvent.getPoint();
                int linha = tabela.rowAtPoint(ponto);
                // Clique duplo
                if (mouseEvent.getClickCount() == 2 && tabela.getSelectedRow() != -1) {
                    Item itemClicado = (Item) modeloTabela.getValueAt(linha, 0);
                    chamaTelaVisualizacaoItem(itemClicado);
                }
            }
        });
    }

    private ItensTableModel getModeloTabela() {
        return this.modeloTabela;
    }

    private void chamaTelaVisualizacaoItem(Item itemClicado) {
        Produto produtoClicado = itemClicado.getProduto();
        if (produtoClicado instanceof ProdutoPronto) {
            VisualizacaoItemProdutoPronto visualizacaoItemProdutoPronto = new VisualizacaoItemProdutoPronto(this.pai, true, itemClicado);
            visualizacaoItemProdutoPronto.setLocationRelativeTo(null);
            visualizacaoItemProdutoPronto.setVisible(true);
        } else {
            VisualizacaoItemProdutoPersonalizado visualizacaoItemProdutoPersonalizado = new VisualizacaoItemProdutoPersonalizado(this.pai, true, itemClicado);
            visualizacaoItemProdutoPersonalizado.setLocationRelativeTo(null);
            visualizacaoItemProdutoPersonalizado.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painelFormulario = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        painelCampos = new javax.swing.JPanel();
        textoValor = new javax.swing.JLabel();
        textoValorPreenchido = new javax.swing.JLabel();
        textoSolicitado = new javax.swing.JLabel();
        textoSolicitadoPreenchido = new javax.swing.JLabel();
        textoEntrega = new javax.swing.JLabel();
        textoEntregaPreenchido = new javax.swing.JLabel();
        textoEstado = new javax.swing.JLabel();
        textoEstadoPreenchido = new javax.swing.JLabel();
        textoComentario = new javax.swing.JLabel();
        painelPainelTextoComentario = new javax.swing.JScrollPane();
        painelTextoComentario = new javax.swing.JTextPane();
        painelItens = new javax.swing.JPanel();
        painelRolavelTabelaItens = new javax.swing.JScrollPane();
        tabelaItens = new javax.swing.JTable();
        painelBotoes = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edição do Pedido");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        painelFormulario.setLayout(new java.awt.GridBagLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Pedido");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        painelFormulario.add(titulo, gridBagConstraints);

        painelCampos.setPreferredSize(new java.awt.Dimension(291, 260));
        painelCampos.setLayout(new java.awt.GridBagLayout());

        textoValor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoValor.setText("Valor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelCampos.add(textoValor, gridBagConstraints);

        textoValorPreenchido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoValorPreenchido.setText("R$ 0,00");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelCampos.add(textoValorPreenchido, gridBagConstraints);

        textoSolicitado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSolicitado.setText("Solicitado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelCampos.add(textoSolicitado, gridBagConstraints);

        textoSolicitadoPreenchido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoSolicitadoPreenchido.setText("00/00/0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelCampos.add(textoSolicitadoPreenchido, gridBagConstraints);

        textoEntrega.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEntrega.setText("Entrega:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelCampos.add(textoEntrega, gridBagConstraints);

        textoEntregaPreenchido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEntregaPreenchido.setText("11/11/1111");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelCampos.add(textoEntregaPreenchido, gridBagConstraints);

        textoEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEstado.setText("Estado:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelCampos.add(textoEstado, gridBagConstraints);

        textoEstadoPreenchido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoEstadoPreenchido.setText("Solicitado");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        painelCampos.add(textoEstadoPreenchido, gridBagConstraints);

        textoComentario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        textoComentario.setText("Comentário:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 30;
        painelCampos.add(textoComentario, gridBagConstraints);

        painelTextoComentario.setEditable(false);
        painelTextoComentario.setMinimumSize(new java.awt.Dimension(62, 66));
        painelTextoComentario.setPreferredSize(new java.awt.Dimension(62, 66));
        painelPainelTextoComentario.setViewportView(painelTextoComentario);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        painelCampos.add(painelPainelTextoComentario, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 10);
        painelFormulario.add(painelCampos, gridBagConstraints);

        painelItens.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        painelRolavelTabelaItens.setMinimumSize(new java.awt.Dimension(16, 100));
        painelRolavelTabelaItens.setPreferredSize(new java.awt.Dimension(452, 200));

        tabelaItens.setModel(this.getModeloTabela());
        tabelaItens.setMinimumSize(new java.awt.Dimension(0, 66));
        tabelaItens.removeColumn(tabelaItens.getColumnModel().getColumn(0));
        painelRolavelTabelaItens.setViewportView(tabelaItens);

        painelItens.add(painelRolavelTabelaItens);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        painelFormulario.add(painelItens, gridBagConstraints);

        painelBotoes.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        painelBotoes.add(botaoVoltar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        painelFormulario.add(painelBotoes, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(painelFormulario, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizacaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VisualizacaoPedido dialog = new VisualizacaoPedido(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPanel painelBotoes;
    private javax.swing.JPanel painelCampos;
    private javax.swing.JPanel painelFormulario;
    private javax.swing.JPanel painelItens;
    private javax.swing.JScrollPane painelPainelTextoComentario;
    private javax.swing.JScrollPane painelRolavelTabelaItens;
    private javax.swing.JTextPane painelTextoComentario;
    private javax.swing.JTable tabelaItens;
    private javax.swing.JLabel textoComentario;
    private javax.swing.JLabel textoEntrega;
    private javax.swing.JLabel textoEntregaPreenchido;
    private javax.swing.JLabel textoEstado;
    private javax.swing.JLabel textoEstadoPreenchido;
    private javax.swing.JLabel textoSolicitado;
    private javax.swing.JLabel textoSolicitadoPreenchido;
    private javax.swing.JLabel textoValor;
    private javax.swing.JLabel textoValorPreenchido;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
