/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.lugar.view;

import com.lugar.controller.OperacoesPedido;
import com.lugar.model.Pedido;
import com.lugar.model.tables.PedidosTableModel;
import com.lugar.view.cliente.VisualizacaoPedido;
import com.lugar.view.funcionario.EdicaoPedido;
import java.awt.Point;
import java.util.List;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JDialog;
import javax.swing.JTable;

/**
 *
 * @author lugar
 */
public class ExibicaoPedidos extends javax.swing.JDialog {

    private java.awt.Frame pai;
    private List<Pedido> listaPedidos;
    private PedidosTableModel modeloTabela;
    private OperacoesPedido operacoesPedido;
    private boolean admin;
    private int idUsuario;

    public ExibicaoPedidos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public ExibicaoPedidos(java.awt.Frame parent, boolean modal, boolean admin, int idUsuario) {
        super(parent, modal);
        this.pai = parent;
        this.admin = admin;
        this.idUsuario = idUsuario;
        this.operacoesPedido = new OperacoesPedido();
        initComponents();

        tabelaPedidos.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent mouseEvent) {
                JTable tabela = (JTable) mouseEvent.getSource();
                Point ponto = mouseEvent.getPoint();
                int linha = tabela.rowAtPoint(ponto);
                // Clique duplo
                if (mouseEvent.getClickCount() == 2 && tabela.getSelectedRow() != -1) {
                    chamaTelaPedido((int) modeloTabela.getValueAt(linha, 0));
                }
            }
        });
    }

    private void atualizaTabela() {
        this.atualizaModeloTabela();
        tabelaPedidos.setModel(this.modeloTabela);
        tabelaPedidos.removeColumn(tabelaPedidos.getColumnModel().getColumn(0));
    }

    private void atualizaModeloTabela() {
        if (this.admin) {
            this.listaPedidos = this.operacoesPedido.buscaTodos();
        } else {
            this.listaPedidos = this.operacoesPedido.buscaTodos(this.idUsuario);
        }
        this.modeloTabela = new PedidosTableModel(listaPedidos);
    }

    private void chamaTelaPedido(int id) {
        JDialog tela;
        if (this.admin) {
            tela = new EdicaoPedido(pai, true, id);
        } else {
            tela = new VisualizacaoPedido(pai, true, id);
        }
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
        this.atualizaTabela();
    }

    public PedidosTableModel getModeloTabela() {
        this.atualizaTabela();
        return modeloTabela;
    }

    /**
     * \
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        painelAcoes = new javax.swing.JPanel();
        botaoVoltar = new javax.swing.JButton();
        painelTabela = new javax.swing.JPanel();
        telaRolavel = new javax.swing.JScrollPane();
        tabelaPedidos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pedidos");
        setMinimumSize(new java.awt.Dimension(700, 466));
        setPreferredSize(new java.awt.Dimension(700, 466));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        painelAcoes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });
        painelAcoes.add(botaoVoltar);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(painelAcoes, gridBagConstraints);

        painelTabela.setLayout(new java.awt.BorderLayout());

        tabelaPedidos.setModel(this.getModeloTabela());
        tabelaPedidos.getTableHeader().setReorderingAllowed(false);
        telaRolavel.setViewportView(tabelaPedidos);

        painelTabela.add(telaRolavel, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 10);
        getContentPane().add(painelTabela, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibicaoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibicaoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibicaoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibicaoPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExibicaoPedidos dialog = new ExibicaoPedidos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JPanel painelAcoes;
    private javax.swing.JPanel painelTabela;
    private javax.swing.JTable tabelaPedidos;
    private javax.swing.JScrollPane telaRolavel;
    // End of variables declaration//GEN-END:variables
}
